NO_SESSION              =       '{"status":"1","error":"SessionId not valid, or was not passed. Please login again."}'
NO_PERMISSION           =       '{"status":"2","error":"Permission denied"}'
NO_FILE                 =       '{"status":"3","error":"File not found."}'
NO_FOLDER               =       '{"status":"4","error":"Folder not found."}'
NO_UPLOAD               =       '{"status":"5","error":"Upload not found."}'
NO_DOWNLOAD             =       '{"status":"6","error":"Download not found."}'
DANGEROUS_INPUT         =       '{"status":"7","error":"Potentially dangerous input detected."}'
FILE_LOCKED             =       '{"status":"8","error":"File is locked by other process."}'
DUPLICATE_FILE_NAME     =       '{"status":"9","error":"Filename already used in this directory."}'
DUPLICATE_FOLDER_NAME   =       '{"status":"10","error":"Foldername already used in this directory."}'
WRONG_LOCK_ID           =       '{"status":"11","error":"Wrong lock_id. Permission denied."}'
FILE_DELETED            =       '{"status":"12","error":"File was deleted."}'
FILE_TO_LARGE_TO_SAVE   =       '{"status":"13","error":"save_file is not allowed with files larger than five (5) MiB."}'
FILE_TO_LARGE_TO_GET    =       '{"status":"14","error":"get_file is not allowed with files larger than five (5) MiB."}'
TIMEOUT                 =       '{"status":"15","error":"Process timed out."}'
DATA_MISSING            =       '{"status":"16","error":"Data section missing."}'
UKNOWN_USER_ID          =       '{"status":"17","error":"Unknown user id."}'
LIST_LEN_DOES_NOT_MATCH =       '{"status":"18","error":"The length of the given lists don\'t match."}'
UNKNOWN_PROPERTY_NAME   =       '{"status":"19","error":"Unknown property name."}'
SYNTAX_ERROR            =       '{"status":"20","error":"Error in argument syntax."}'
TYPES_NOT_MATCHING      =       '{"status":"21","error":"Wrong argument type passed."}'
COPY_ERROR              =       '{"status":"22","error":"An error happened while copying the file contents."}'
BASE64_ERROR            =       '{"status":"23","error":"Error in base64 encoding."}'
INVALID_USER_ID         =       '{"status":"24","error":"User id is invalid."}'
UKNOWN_GROUP_ID         =       '{"status":"25","error":"Unknown group id."}'
DOWNLOAD_FINISHED       =       '{"status":"26","error":"Download finished."}'
DUPLICATE_USERNAME      =       '{"status":"27","error":"Duplicate username."}'
INVALID_VALUE           =       '{"status":"28","error":"Invalid value."}'

# WEB SERVER ERROR
INTERNAL_SERVER_ERROR   =       '{"status":"500","error":"Internal Server Error."}'
UNKNOWN_RESOURCE        =       '{"status":"404","error":"Unknown resource."}'
FORBIDDEN_METHOD        =       '{"status":"405","error":"Forbidden Method."}'
BAD_REQUEST             =       '{"status":"400","error":"Bad Request."}'
INVALID_COMMAND         =       '{"status":"401","error":"Command not valid."}'
UNKNOWN_ERROR           =       '{"status":"402","error":"An unknown error happened."}'

WRONG_CREDENTIALS       =       '{"status":"101","error":"Wrong Credentials."}'


